import type { Metadata } from "next";
import './globals.css';
import Header from './components/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='pt-BR'>
      <body>
        <header>
          <Header />
        </header>
        <main>{children}</main>
        <footer>
          <p>Todos os direitos reservados</p>
        </footer>
      </body>
    </html>
  );
}
